apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cis188.penn@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      # TODO: change to http01
      # - selector: {}
      #   dns01:
      #     cnameStrategy: Follow
      #     cloudflare:
      #       email: pennappslabs@gmail.com
      #       apiKeySecretRef:
      #         name: cloudflare-api-key-secret
      #         key: api-key
